name: Run Unittests
on: [push, pull_request]

jobs:
  dubtest:
    name: Dub Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dc: [dmd-latest, ldc-latest]
        exclude:
        - os: windows-latest
          dc: dmd-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Run workspace-d tests
        run: dub test :workspace-d
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.12'

      - name: serialization tests
        run: dub test :protocol
        timeout-minutes: 5
        env:
          # shouldn't break other OSes
          MACOSX_DEPLOYMENT_TARGET: '10.12'

      - name: LSP tests
        run: dub test :lsp
        timeout-minutes: 5
        env:
          # shouldn't break other OSes
          MACOSX_DEPLOYMENT_TARGET: '10.12'

      - name: serverbase tests
        run: dub test :serverbase
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.12'

      - name: build minimal server
        run: dub build --root=null_server
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.12'

      - name: test minimal server
        run: dub run --root=null_server_test
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.12'

      - name: Run tests
        run: dub test
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.12'

      - name: Run standalone tests
        run: ./runtests.sh
        working-directory: ./test
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.12'
