name: Run Unittests
on: [push, pull_request]

jobs:
  dubtest:
    name: Dub Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dc: [dmd-latest, ldc-latest]
        exclude:
        - os: windows-latest
          dc: dmd-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - name: Install D compiler
        uses: mihails-strasuns/setup-dlang@v0.3.1
        with:
          compiler: ${{ matrix.dc }}

      - name: dub upgrade
        uses: WebFreak001/dub-upgrade@v0.1.0

      - name: Run tests
        run: dub test
        env:
          # shouldn't break other OSes
          MACOSX_DEPLOYMENT_TARGET: '10.12'

      - name: cache dependency binaries
        uses: WebFreak001/dub-upgrade@v0.1.0
        with:
          store: true
